### ISSUE TITLE
Vorschlag : Balken übernehmen Formatierungen der Measures

### ISSUE THREAD

**Issue by MarcSalomon-SB** [AuxilManagementGmbH/WasserfallExtended#1]
Hallo,

tolles Visual, aber es würde helfen wenn die Formatierung der Werte eines Balken (wenn nichts angegeben wird) vom Measure übernommen werden. Würde sich insbesondere bei dynamisch formatierten Measures gut machen.

Gruß
Marc

**Comment by lennartwollatz** [comment]
Hallo @MarcSalomon-SB, 

dein Vorschlag ist hervorragend und wurde mit aufgenommen. In der neue Version 3.3.1.1 wird dieses Feature mit eingebaut sein. 
Release ist heute. Verfügbar aufgrund der langen Wartezeit bei Microsoft in ca. 2-2,5 Wochen. 

Beste Grüße
Lennart

**Comment by lennartwollatz** [comment]
Neue Version wurde hochgeladen und ist in 2-2,5 Wochen verfügbar
